### ISSUE TITLE
Most efficient way to filter results based on specific key/value pair

### ISSUE THREAD

**Issue by chadokruse** [dominictarr/JSONStream#106]
First, great work on this...much appreciated!

I'm parsing a 1GB JSON file that generally looks like this:

```
{
    "all": [
        {
            "foo": "aaa",
            "target": "no"
        }, {
            "foo": "bbb",
            "target": "yes"
        }, {
            "foo": "ccc",
            "target": "no"
        }
    ]
}
```

Is there a more simplistic way of limiting results passed downstream to just those where `"target" == "yes"`, other than using `event-stream`?

Using a more real-life example, the event-stream code, of course, would be as follows:

```
var request    = require("request");
var JSONStream = require("JSONStream");
var es         = require("event-stream");
 
request("https://s3.amazonaws.com/irs-form-990/index.json")
  .pipe(JSONStream.parse('AllFilings.*')) //Same as : (['AllFilings',true])
  .pipe(es.mapSync(function (data) {
    if(data.URL && data.URL.length > 0 && data.FormType == '990PF') {
      console.log(data);
      //return all objects with a data.URL and FormType of 990PF
    }
  }));
```
Thanks!

*In case it helps anyone stumbling upon this via Google, the JSONPath expression would be* `$.all[?(@.target=='yes')]`.

**Comment by dominictarr** [comment]
Sorry, no I don't have a better way to do it than that.

It's interesting that you use the JSONPath expression though, when I was first implementing this, I did investigate several implementations of JSONPath-like things, but none of them where sufficiently stream-oriented to adapt to streaming json.
It would be a really great feature though.

oh, I have been working on https://github.com/dominictarr/map-filter-reduce
which is a streaming query language, that could be applied to this, this is certainly still a thing which is in _development_, though

**Comment by chadokruse** [comment]
Right on, I appreciate the quick reply! The map-filter-reduce project looks like a fun one.

Using event-stream works great, was just making sure I wasn't missing something after reading the docs. I'll go ahead and close this ticket. 

Thanks again!
