### ISSUE TITLE
If there are typescript typings for this module, it would be nice if it were in the readme

### ISSUE THREAD

**Issue by ORESoftware** [dominictarr/JSONStream#139]
If there are TS typings for this, it would help to document that something like so:

install
```
npm install JSONStream
```
install types
```
npm install -D @types/JSONStream
```

if there are not types, then this is a feature request for TS typings!

**Comment by dominictarr** [comment]
sure, please make a PR.

**Comment by EricByers** [comment]
There currently cannot be types for this module because DefinitelyTyped (who controls the @types/ on npm) will not let any non-lowercase modules made, this means even if it was added (as jsonstream lowercase) it wouldn't work :(.

See: https://github.com/dominictarr/JSONStream/issues/128

**Comment by ORESoftware** [comment]
@EricByers ah you are under the mistaken impression that you need to publish to @types/X to get TS typings in place. You don't need to do that at all tmk.

All you need to do is include the *.d.ts files in this project itself, when publishing to NPM. You almost certainly need just one .d.ts file, let's say index.d.ts.

And then in your package.json, point "types" or "typings" to the main exported types file, let's say "index.d.ts".

Make sense?

**Comment by ORESoftware** [comment]
To further elucidate, I get this error when transpiling with TS:

`index.ts(16,29): error TS7016: Could not find a declaration file for module 'JSONStream'. '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman-daemon/node_modules/JSONStream/index.js' implicitly has an 'any' type.`

so all you need to do is generate index.d.ts, and you will be good to go :)

**Comment by EricByers** [comment]
I understand that process, I just wasn't expecting the app owner to accept it in and maintain it, most repos if they are not already written in TS.

**Comment by EricByers** [comment]
If you're willing to have it as any, you can import it as that way, and not worry about types at all.  TS added support a few versions back.

**Comment by ORESoftware** [comment]
I think he made it clear that we could submit a PR to create index.d.ts, without turning index.js into index.ts.
