### ISSUE TITLE
JSON Parse

### ISSUE THREAD

**Issue by armadeas** [dominictarr/JSONStream#142]
hi i have somthing Web Stream API but this is not Pure JSON Data
the Data Like this
id: 0
data: {"code":"start","data":1}

id: 0
data: {"code":"server","data":["192.168.188.192","9333"]}

id: 0
data: {"code":"Create","data":1}

Attempting to connect to '192.168.188.192' on port '9333'...
id: 0
data: {"code":"Connect","data":1}

id: 1503388899
data: {"code":"sending","data":"R|LT|1|1\r\n"}

id: 1503388899
data: {"code":"counter","data":0}

how i parse this data to Json ?

**Comment by dominictarr** [comment]
JSONStream does not implement that, maybe there is a module for it though? or try asking on stackexchange?
