### ISSUE TITLE
Why do you put mixpanel stuff in this repository?

### ISSUE THREAD

**Issue by ImanMh** [dominictarr/JSONStream#150]
Today I found some ```mixpanel``` requests in my developer tools and when I followed it up I found that this repo is putting a ```mixpanel``` script inside my website. 

```
<script type="text/javascript" async="" src="https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js"></script>
```

I found this file in your repo: 
https://github.com/dominictarr/JSONStream/blob/b7c01ee67fc3824a9038eb7a41899376f5bd99dc/test/fixtures/all_npm.json

Line: 2177 -> 2179

I think it's a mistake, since it's in your test directory it should not even be loaded. There are multiple packages using this project as dependency so I'm not sure it's a problem with this project or not. Please check this issue.

**Comment by doowb** [comment]
That's just a JSON file that's used in tests. It only contains ids and names of npm packages.

> since it's in your test directory it should not even be loaded.

True, so something in your build or bundler is probably loading it or something else is adding mixpanel.

**Comment by ImanMh** [comment]
I found that this is just an accident, There was a plug-in adding mixpanel code to my codes. Anyway I found your mixpanel API key in that file. If it's something private remove it. Have a nice day.
