### ISSUE TITLE
FYI: "event-stream" dependency is backdoored, apparently starting from v3.3.5

### ISSUE THREAD

**Issue by vladimiry** [dominictarr/JSONStream#167]
https://github.com/dominictarr/event-stream/issues/116

Preliminary analysis:
- https://github.com/dominictarr/event-stream/issues/116#issuecomment-441749105
- https://github.com/dominictarr/event-stream/issues/116#issuecomment-441759047

**Comment by doowb** [comment]
Thanks for the warning.

This library uses `event-stream` in `devDependencies` and it's specified as `0.7.0`, which means that only versions `>= 0.7.0 and < 0.8.0` will be installed.

I'm going to close this since there's nothing to do here, but that's again for the warning.
