### ISSUE TITLE
object mode?

### ISSUE THREAD

**Issue by giladgray** [dominictarr/JSONStream#55]
Is this plugin compatible with streams in object mode? I'm working on a Gulp plugin that parses and transforms a series of JSON files ([palantir/gulp-bower-overrides](http://github.com/palantir/gulp-bower-overrides)) and this plugin looks like a promising way to process the JSON but I can't figure out how to make it work with Vinyl files.

`through2` supports object mode via `through.obj`, but the classic `through` module used here does not seem to. Perhaps that's part of the issue?

**Comment by dominictarr** [comment]
Is classic streams there is no distinction between object and non object mode.
It's always object mode.

**Comment by slang800** [comment]
this issue should be closed
