### ISSUE TITLE
Not able to parse the json file

### ISSUE THREAD

**Issue by siddhsuper** [dominictarr/JSONStream#56]
# Not able to parse the json file [I am new to javascript]

This is my json file location = './jsons/rep_controller.json':
{
  "apiVersion": "v12",
  "kind": "SController",
  "id": "siddhweb-controller",
  "labels": {
    "name": "siddhee"
  }
}

================================
```javascript
function loadJSONData(next) {
  logger.info('loadJSONData');
  var getStream = function () {
    var jsonData = './jsons/rep_controller.json',
        stream = fs.createReadStream(jsonData, {encoding: 'utf8'}),
        parser = JSONStream.parse('*');
        return stream.pipe(parser);
    };

getStream().on('data', function(data) {
 logger.info('received: - ', data);
});
};

```

Getting the error undefined

**Comment by dominictarr** [comment]
for such a small file there is no advantage to streaming.
Just read it and then parse the whole thing with `JSON.parse(str)`

**Comment by siddhsuper** [comment]
Actually the problem was in the JSON file, and not able to do 
```javascript
 JSON.parse(str)
```
That's why I thought JSONStream will work for me.

Anyways thanks a ton for your immediate reply :+1:
