### ISSUE TITLE
npm publish latest version

### ISSUE THREAD

**Issue by 2do2go** [dominictarr/JSONStream#59]
Latest version available at npm is 0.10.0. Could you publish the latest one (1.0.1)?

**Comment by KenanY** [comment]
@2do2go This is blocked by https://github.com/npm/npm/issues/7195.

**Comment by okv** [comment]
How about to lowercase the package name? Or is there another way to resolve the situation?

**Comment by Aeal** [comment]
You can work around this issue by using a github url for the dependency rather than a semantic version.

**Comment by okv** [comment]
I know, thanks. But it's not so good as semantic version - it reinstalls every time when you do `npm install`.

**Comment by Aeal** [comment]
I understand its not ideal that's why its a workaround.

**Comment by dominictarr** [comment]
Okay this is now published as jsonstream@1.0.3 !

**Comment by okv** [comment]
:+1:
