### ISSUE TITLE
How to parse json from array

### ISSUE THREAD

**Issue by donniev** [dominictarr/JSONStream#62]
Pardon the newbie question.

I receive data from a via a third party api

It comes back in the form
```
{ asOfDate:xxx,
   loans:[
        { a:x,
          b:y,
          …
       },
        { a:xx,
          b:yy,
         …
       },
      …
     ]
}
```
My goal is to steam each element of the array
and process it as it comes in rather than building
the entire object and iterating over each element
in the array.

Can JSON stream help with this or do you have other suggestions.

FWiW each row goes into a mongo collection.

**Comment by Poetro** [comment]
`JSONStream.parse('loans.*')`

**Comment by donniev** [comment]
Thanks,
That works just fine.
I knew it was a newbie issue :-).
