### ISSUE TITLE
Incoming data from the stream isn't fully parsed

### ISSUE THREAD

**Issue by tciuro** [dominictarr/JSONStream#65]
The following snippet:

	var request = require('request')
	  , JSONStream = require('JSONStream')
	  , es = require('event-stream')

	var parser = JSONStream.parse(['rows', true])
		req = request({url: 'http://127.0.0.1:10355/db/_all_docs?include_docs=true'}),
		logger = es.mapSync(function (data) {
			console.log(data)
			console.log('*********************************');
	    	return data  
	  	});

	req.pipe(parser)
	parser.pipe(logger)

Returns data in the following format:

	*********************************
	{ id: '_design/test',
	  key: '_design/test',
	  value: { rev: '1-18fca9bd97ed51926f4fe9030d81b6c2' },
	  doc: 
	   { _id: '_design/test',
	     _rev: '1-18fca9bd97ed51926f4fe9030d81b6c2',
	     views: 
	      { 'test_results-all_devices-for-test-for-integration': [Object],
	        'tests-for-integration-by-device': [Object],
	        'by-path': [Object],
	        'all-tests': [Object] },
	     language: 'javascript' } }
	*********************************

Notice the `[Object]` references. How can we read fully parsed objects from the stream? Thanks!

**Comment by KenanY** [comment]
@tciuro That's the fault of `console.log`, not JSONStream. It does that after a certain depth:

``` js
console.log({a:{b:{c:{d:{}}}}});
// => { a: { b: { c: [Object] } } }
```

What you might be looking for is [`util.inspect`](https://nodejs.org/api/util.html#util_util_inspect_object_options) with a higher `depth` value:

``` js
var util = require('util');

util.inspect({a:{b:{c:{d:{}}}}}, {depth: null});
// => '{ a: { b: { c: { d: {} } } } }'

```

**Comment by tciuro** [comment]
Ah! Of course! Thanks Kenan!
