### ISSUE TITLE
Duplicate, mismatched modules on npm

### ISSUE THREAD

**Issue by callum** [dominictarr/JSONStream#68]
![screen shot 2015-05-07 at 17 39 54](https://cloud.githubusercontent.com/assets/1245446/7520658/2b0667ec-f4e0-11e4-82c6-a4c633a66141.png)

Browserify looks for a specific version of JSONStream here https://github.com/substack/node-browserify/blob/master/package.json#L48

Is there a case sensitivity issue going on? This happened after upgrading node and npm. It fails on install because it tries to install JSONStream and not jsonstream where the version is less than specified by browserify.

**Comment by jwhitehorn** [comment]
+1 just ran into this as well

**Comment by callumacrae** [comment]
same

**Comment by jgoz** [comment]
This wreaks havoc on Windows/case insensitive filesystems when `JSONStream` and `jsonstream` are both dependencies. The `npm` cache gets populated with one of these and then it can't find the other.

My recommendation would be to cross-publish all versions to `JSONStream` and `jsonstream` until the former is no longer a common dependency.

**Comment by danemacaulay** [comment]
+1

**Comment by Sanjo** [comment]
:+1: I can no longer install cucumber that depends on browserify.

**Comment by danemacaulay** [comment]
this is not a problem in linux environments, think @callum is right about case sensitivity. 
i believe a resolution would be to remove the older `JSONStream` from the npm registry

**Comment by andrewevansmith** [comment]
Is there anything we can do in the meantime?  It affects cordova and phonegap as well.

**Comment by danemacaulay** [comment]
i used a linux vm to install the dependencies

**Comment by Sanjo** [comment]
Upgrading to the latest browserify solved it for me. Here is what they have done: https://github.com/substack/node-browserify/pull/1247. I guess each package that depends on JSONStream should do that dependency update.

**Comment by zertosh** [comment]
browserify@10.1.2 won't have this problem. it seems to only affect 5.0.0-10.1.1. But cross-publishing doesn't seem to be possible because JSONStream (w/ caps) isn't updatable https://github.com/npm/npm/issues/7195

**Comment by cmmcleod** [comment]
+1

**Comment by teddyhwang** [comment]
+1

**Comment by butterdave** [comment]
+1

**Comment by lalehstp** [comment]
+1

**Comment by mlakhia** [comment]
+1. Updating browserify to 10.1.2 solved the issue for me

**Comment by jwhitehorn** [comment]
Updating browserify works, but other dependencies like grunt-browserify are still effected.

I tried doing an `npm install` from a case-sensitive OS X disk image, but that still didn't resolve this issue for me.

**Comment by carbontwelve** [comment]
This has stopped elixir from installing as well as reported here http://laravel.io/forum/05-07-2015-elixir-wont-install?page=1

**Comment by ckrotcov** [comment]
+1

**Comment by stephenliberty** [comment]
+1

**Comment by calvinmetcalf** [comment]
JSONStream is a weird case because it has capitals which are no longer allowed but it seemed to have been grandfathered in, the JSONStream/jsonstream thing has been around for a while and previously didn't cause any issues

**Comment by stan229** [comment]
+1 seeing this for installing the latest cordova, phonegap and Ionic (depends on Cordova)

See reports here: 
http://stackoverflow.com/questions/30107474/error-installing-cordova
http://forum.ionicframework.com/t/issues-installing-cordova-using-npm-install/22573/5
http://stackoverflow.com/questions/30107556/trouble-installing-phonegap-no-compatible-version-found-jsonstream-1-0-3

**Comment by dominictarr** [comment]
I can't remove JSONStream, that would break thousands of modules.

I had to publish jsonstream because npm broke my ability to update JSONStream https://github.com/npm/npm/issues/7195

They have been saying they would fix it, so that legacy uppercase modules could still publish, but not new modules (this had been the behavior for a long time, until just recently...)

I was then unable to publish new versions of JSONStream, however, pull requests where coming in,
so eventually, due to popular demand I published it as `jsonstream` https://github.com/dominictarr/JSONStream/issues/59

this this happened. so far there are only 8 things that depend on jsonstream (though, one of them is browserify, which everyone uses)

**Comment by TheSharpieOne** [comment]
Looking at npm/npm#7195, the validation is all done in npm and not on the server (as they were discussing adding server side validation).  Based on that, would it be possible to install an older version of npm to push up an update to JSONStream to cross-publish?

**Comment by zertosh** [comment]
To @TheSharpieOne's point... The validation seems to happen [here](https://github.com/npm/normalize-package-data/blob/a168f6153570465db33d96601576b612a63ed446/lib/fixer.js#L317-L325)

Though I don't know if it's right for @dominictarr to patch his npm so he can publish.

**Comment by dominictarr** [comment]
Okay I published JSONStream at 1.0.2 and 1.0.3 does this still happen?

**Comment by zertosh** [comment]
@dominictarr IT WORKS!!!!

**Comment by danemacaulay** [comment]
thanks :+1:

**Comment by vmlellis** [comment]
Thanks!

**Comment by TheSharpieOne** [comment]
Crisis [mostly] averted!

**Comment by wolfius** [comment]
Great! :)

**Comment by zertosh** [comment]
You get these warnings on OS X, but browserify works:

```
npm ERR! missing: jsonstream@^1.0.3, required by browser-pack@4.0.3
npm ERR! extraneous: JSONStream@1.0.3 /Users/andres/Downloads/node_modules/browserify/node_modules/browser-pack/node_modules/JSONStream
npm ERR! missing: jsonstream@^1.0.3, required by deps-sort@1.3.7
npm ERR! extraneous: JSONStream@1.0.3 /Users/andres/Downloads/node_modules/browserify/node_modules/deps-sort/node_modules/JSONStream
npm ERR! missing: jsonstream@^1.0.3, required by insert-module-globals@6.4.1
npm ERR! extraneous: JSONStream@1.0.3 /Users/andres/Downloads/node_modules/browserify/node_modules/insert-module-globals/node_modules/JSONStream
npm ERR! missing: jsonstream@^1.0.3, required by module-deps@3.7.11
npm ERR! extraneous: JSONStream@1.0.3 /Users/andres/Downloads/node_modules/browserify/node_modules/module-deps/node_modules/JSONStream
```

**Comment by dominictarr** [comment]
okay next step is just to get browserify to go back to JSONStream

**Comment by zertosh** [comment]
@dominictarr Ok... I'll switch browserify and the various deps over now

**Comment by englercj** [comment]
I'm now getting shasum errors, cleaning cache for `jsonstream` and `JSONStream` doesn't seem to help:

```
npm ERR! shasum check failed for /tmp/npm-31132-1afc4346/.../j/jsonstream/_attachments/jsonstream-1.0.3.tgz
npm ERR! Expected: 728544189438b7b9dd2184392581861ebabd9621
npm ERR! Actual:   ff2d49c4f479b5bbcdf9f9e56c841cf87f0efa1d
```

**Comment by othiym23** [comment]
@englercj If you can, upgrade to npmE 2.0.0, which has a fix for this issue (older versions of npmE just went ahead and lowercased all of the package names when the follower was replicating them, which is pretty obviously what's causing the problem here).

The easiest way to upgrade the npmE distribution is:

1. back up `/etc/npme`
2. back up the CouchDB files, which are in `/var/lib/couchdb`
3. delete `/etc/npme/.license.json`
4. `cd ~/ && npm cache clear && npm install npme`, which will do a full reinstall, prompt you for creds, etc
5. `sudo service couchdb restart`

If that doesn't get you sorted out, or is impossible, drop a line to support@npmjs.com and we'll get you sorted out.

**Comment by ryanbahniuk** [comment]
Is there a plan here either with npm or with other packages that use JSONStream as a dependency? I know Browserify updated quickly (thanks for that), but my repo has multiple other dependencies that rely on this package. I'm sure I'm not alone here.

**Comment by rmg** [comment]
@dominictarr it looks like the conclusion to all this is that `JSONStream` is the canonical form, correct? How about marking the 2 existing `jsonstream` releases as deprecated so that anyone using them gets notified?

**Comment by dominictarr** [comment]
done.
