### ISSUE TITLE
Callback when done.

### ISSUE THREAD

**Issue by BasVanDerHeijden** [dominictarr/JSONStream#69]
I'm using the JSONStream to parse a very large JSON file and index it into ElasticSearch.
What I want to do, is know when all rows have been passed. 

In short, I'm doing: parser = JSONStream.parse('*');

I'm piping the data through your other library (event stream) as follows:

parser.pipe(es.mapSync(function (data) { }).

Then, for each document traversed, I'm indexing that document to ElasticSearch.

Now: I want to know the number of rows inserted. How do I do this pragmatically?

thanks in advance.

**Comment by Poetro** [comment]
Pipe it through a PassThrough stream and count the number of elements that goes through.

**Comment by Poetro** [comment]
Something like:
```javascript
var passThrough = new stream.PassThrough();
var counter = 0;
passThrough. _transform = function (chunk, encoding, cb) {
  counter++;
  cb(null, chunk);
}
passThrough.on('finish', function () {
  passThrough.emit('collected', counter);
});
```

**Comment by BasVanDerHeijden** [comment]
Thanks!

**Comment by martinib77** [comment]
Sorry, i'm trying to use your solution but have the error:
Invalid non-string/buffer chunk
How can i solve this? thanks in advance

**Comment by dominictarr** [comment]
@martinib77 you are writing something to JSONStream.parse that is not a string or a buffer. most likely it's null or undefined?

**Comment by martinib77** [comment]
it's a json file. I'm using 0.x version of your library and working ok. When i updated the library to 1.x, i'm missing the 'root' event to know when it has finished so i wanted to try this solution but didn't work.
How can i solve detect when the file reading is done?

**Comment by dominictarr** [comment]
@martinib77 I'm sorry, the 'root' event was removed in 1.0.0 (that feature had to go because it was causing memory leak problems)

Can you try JSONStream@<1

**Comment by martinib77** [comment]
Hi, sorry for the long time from my last question.
I'm going back to version 1.x because according to my tests, it solves some poblems with the reading of float numbers.
I'm using the 'end' event instead of 'root'. It's that ok to know when the file is completely readed ?.
Thanks.

**Comment by dominictarr** [comment]
@martinib77 yes 'end' should be fine.
