### ISSUE TITLE
Do not work on Windows

### ISSUE THREAD

**Issue by vicentedealencar** [dominictarr/JSONStream#85]
Hi,

I am having trouble on Windows.

`npm i -g JSONStream`
`curl https://registry.npmjs.org/browserify | JSONStream 'versions.*.dependencies'`

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: Invalid JSON (Unexpected "S" at position 4 in state STOP)
    at Parser.proto.charError (D:\npm\node_modules\JSONStream\node_modules\jsonparse\jsonparse.js:78:16)
    at Parser.proto.write (D:\npm\node_modules\JSONStream\node_modules\jsonparse\jsonparse.js:104:23)
    at Stream.<anonymous> (D:\npm\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (D:\npm\node_modules\JSONStream\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

At first I got the same error on react-stdio and opened this issue https://github.com/mjackson/react-stdio/issues/2

**Comment by dominictarr** [comment]
but what json output did you get from curl?
that looks like a parse error.
I'd be fairly surprised if this error was caused by JSONStream, because there isn't any thing OS dependent in.

**Comment by gchauvet** [comment]
Under Linux : no issue with your example. Can you send us the JSON output result ?
curl https://registry.npmjs.org/browserify > browserify.json

I suspect a Windows charset problem.

**Comment by dominictarr** [comment]
@vicentedealencar I won't get the same json output from that because I don't run windows, can you attach it?

**Comment by vicentedealencar** [comment]
when I run `curl -?` I realise that this is an alias for powershell `Invoke-WebRequest` and the output looks like this:

```


StatusCode        : 200
StatusDescription : OK
Content           : {"_id":"browserify","_rev":"1632-40c1a4214800b67576e82cb5c455fdc5","name":"browserify","description":"browser-
                    side require() the node way","dist-tags":{"latest":"13.0.0"},"versions":{"0.0.1":{"name":"...
RawContent        : HTTP/1.1 200 OK
                    Age: 51
                    Connection: keep-alive
                    X-Served-By: cache-atl6230-ATL
                    X-Cache: HIT
                    X-Cache-Hits: 1
                    X-Timer: S1453151868.771444,VS0,VE2
                    Vary: Accept
                    Accept-Ranges: bytes
                    Content-Length...
Forms             : {}
Headers           : {[Age, 51], [Connection, keep-alive], [X-Served-By, cache-atl6230-ATL], [X-Cache, HIT]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 857210
```

this explains the Unexpected "S"

I found a reliable curl.exe that is shipped with git, and it worked. Sorry about that.

The thing is I opened this issue because of mjackson/react-stdio#2 and it is not related to curl. Can you help with that?

**Comment by dominictarr** [comment]
yup, there you go... it's probably basically the same problem somewhere in that thing. somewhere it shells out to curl, which is incompatible on windows. the portable solution would be to use `request` intsead, or something like that.
