### ISSUE TITLE
"this.stack[k].value = null" regression after adding "use strict"

### ISSUE THREAD

**Issue by odzb** [dominictarr/JSONStream#88]
The issue that is described at https://github.com/hcoona/hexo-renderer-asciidoc/issues/3 is a consequence of adding the "use strict" directive to JSONStream. The problem goes away when "use strict" is removed (e.g. by using version 1.0.6 instead of 1.0.7).

**Comment by dominictarr** [comment]
can we make that problem into a test case?

**Comment by gchauvet** [comment]
Sound like dominictarr/JSONStream/pull/82

**Comment by dominictarr** [comment]
fixed in 1.1.2
