### ISSUE TITLE
JSONStream or jsonstream?

### ISSUE THREAD

**Issue by jden** [dominictarr/JSONStream#89]
I noticed this module is published on npm as both JSONStream and jsonstream- which is canonical, and which will received latest updates?

(And consider putting a deprecation warning on the other)

Thanks!

**Comment by dominictarr** [comment]
done.

JSONStream is cannocal.
capital letters are now verboten in the npm registry, so never gonna give that up.

**Comment by jden** [comment]
a renegade til the end, I love it :)

thanks!
