### ISSUE TITLE
JSONStream.parse() on a collection of individual JSON objects

### ISSUE THREAD

**Issue by sarus** [dominictarr/JSONStream#94]
Is it possible to use JSONStream.parse() on a collection of individual JSON objects that are being streamed in?

In other words my stream looks like:

```
{"key":"value"}{"key":"value"}{'key":"value"}
```
(note that it is not wrapped in an array)

So far trying to do `JSONStream.parse('*')` does not return any data and I'm assuming it's because my data is not wrapped in an array.   

I have been able to do the following but it doesn't seem very efficient haha:

```
stream.pipe(JSONStream.stringify(false)).pipe(split()).on('data', function(line){
    var row = JSON.parse(line);
});
```

**Comment by dominictarr** [comment]
Ah, that is a bit weird. if you have control of the input format, it's much better to have line delimited json,

```
{"key":"value"}
{"key":"value"}
{'key":"value"}
```

Then just pipe that to `split('\n', null, JSON.parse)` and you'll get the js objects.

Using JSONStream is significantly slower than splitting by lines and then using `JSON.parse` on each line. I'd only recommend using JSONStream if you are consuming a JSON source that you do not control or must be valid return valid JSON for some other reason.

That said, try `JSONStream('')`... you ought to be able to get this to work, and I'd merge a PR that added this.

**Comment by santigimeno** [comment]
Maybe I'm missing something obvious, but isn't this case already supported? See: https://github.com/dominictarr/JSONStream/blob/master/test/multiple_objects.js

**Comment by dominictarr** [comment]
@santigimeno i think the problem is that in this case, he doesn't want to drill into the objects, but just stream a bunch of appended objects, so the path to match is empty...

**Comment by sarus** [comment]
Thanks so much for your assistance.  I did not have control of the input stream and just realized that it was already being passed as an object!  I feel really dumb haha.  Thank you for your help!
