### ISSUE TITLE
Piping entire json result of Watson Speech

### ISSUE THREAD

**Issue by vondiplo** [dominictarr/JSONStream#98]
I'd like to be able to stream a stringified resprenstation of the entire watson speech api response, and not just the transcript. Perhaps instead of the current code line - 
`self.push(data.results[0].alternatives[0].transcript, 'utf8'); `

Could be modified to - 

`self.push(JSON.stringify(data.results[0]), 'utf8')`

**Comment by dominictarr** [comment]
did you post this issue on the wrong repo?

**Comment by vondiplo** [comment]
I'm sorry, my mistake. I must have been multitasking :( My apologies.

**Comment by dominictarr** [comment]
no problem!
